version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    env_file:
      - .env.production
    volumes:
      - ./uploads:/app/uploads
      - ./prisma:/app/prisma
    restart: unless-stopped
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
